Links can now go to github commits

diff --git a/bin/git-graphviz b/bin/git-graphviz
--- a/bin/git-graphviz
+++ b/bin/git-graphviz
@@ -14,6 +14,14 @@ root_dir=$(dirname "$0")/..
 . "$root_dir"/share/wrtools-core/fail.bash
 . "$root_dir"/share/wrtools-core/temp.bash
 
+#HELP:  --url-at-remote=$remote-name: point commits to URLs based on a remote repo
+unset url_at_remote
+opt_url_at_remote () {
+    (( $# == 1 ))|| fail "$FUNCNAME expects 1 arg, a remote name"
+    [[ -z ${url_at_remote+is-set} ]] || fail "$Option --url-at-remote can only be used once"
+    url_at_remote=$1
+}
+
 OPTIND=1
 while getopts :fhkvs:-: OPTION
 do
@@ -29,11 +37,9 @@ do
                 help=* | keep-temps=* | verbose=* ) 
                     fail "No argument expected for long option \"${OPTARG%%=*}\"";;
 
-#                format=* ) opt_format "${OPTARG#*=}";;
-#                param=* ) opt_param "${OPTARG#*=}";;
-#                schema=* ) opt_schema "${OPTARG#*=}";;
-#                format | param | schema )
-#                    fail "Missing required argument for long option \"$OPTARG\"";;
+                url-at-remote=* ) opt_url_at_remote "${OPTARG#*=}";;
+                url-at-remote )
+                    fail "Missing required argument for long option \"$OPTARG\"";;
                 
                 * ) fail "Unexpected long option \"$OPTARG\"";;
             esac;;
@@ -54,14 +60,25 @@ fi
 
 temp_make_dir git_graphviz
 
+url_format="graph.html"
+if [[ -n ${url_at_remote+is-set} ]]
+then git remote show "$url_at_remote" > "$git_graphviz"/remote_show.txt || fail "Remote $url_at_remote not found"
+     sed -e 's/^  Fetch URL: \(.*\)$/\1/p;d' < "$git_graphviz"/remote_show.txt > "$git_graphviz"/remote_url.txt
+     remote_url=$(cat "$git_graphviz"/remote_url.txt)
+     if [[ $remote_url == https://github.com/* ]]
+     then printf -v url_format "%s/commit/%%H" "${remote_url%.git}"
+     else fail "I don't know how to render remote $remote_url"
+     fi
+fi
+
 {
     cat <<EOF
 digraph git_graph {
-    edge [dir=back];
-    node [shape=box, style=rounded];
+    edge [fontname = "Helvetica", fontsize = 10, dir = back];
+    node [fontname = "Helvetica", fontsize = 10, width = 0, height = 0, shape=box, style=rounded];
 EOF
 
-    git log --pretty="format: REALQUOTE\`'%h\`'REALQUOTE [tooltip=REALQUOTE\`'%s\`'REALQUOTE URL=REALQUOTE\`'graph.html\`'REALQUOTE];" "$@" \
+    git log --pretty="format: REALQUOTE\`'%h\`'REALQUOTE [tooltip=REALQUOTE\`'%s\`'REALQUOTE URL=REALQUOTE\`'$url_format\`'REALQUOTE];" "$@" \
       | sed -e "s/\"/HIDDENQUOTE/g" \
       | m4 --define=REALQUOTE="\"" --define=HIDDENQUOTE="\\\""
     
